print("HAI SELAMAT DATANG DI RUANGAN GUA (rangga-dev)")
print("KELAS GUA INI TUJUANNYA UNTUK MEMPERLIHATKAN PYTHON ITU BISA UNTUK APA AJA SIH?")

print("SEBELUM KALIAN TERJUN KE DUNIA PYTHON, KALIAN HARUS TAU TENTANG PYTHON, CARA KERJANYA, KEGUNNAANYA, DLL")