print("TYPE2 DATA")

print("STRING DIGUNAKAN UNTUK MEMBUAT TEKS ATAU SEBUAH KARATER")
print("INTEGER DIGUNAKAN UNTUK MEMBUAT SEBUAH ANGKA DESIMAL ATAU SATUAN")
print("FLOAT DIGUNAKAN UNTUK MEMBUAT SEBUAH ANGKA YANG MENGGUNKAN KOMA .")
print("BOLEAN DIGUNAKAN UNTUK MEMBUAT PERNYATAAN TRUE OR FALSE")